# Creation of Tables: 

CREATE TABLE PUBLISHER(
  NAME VARCHAR(25) PRIMARY KEY,
  ADDRESS VARCHAR(50),
  PHONE VARCHAR(13));

CREATE TABLE BOOK(
  BOOK_ID INTEGER PRIMARY KEY,
  TITLE VARCHAR(20),
  PUB_YEAR VARCHAR(20),
  PUBLISHER_NAME REFERENCES PUBLISHER(NAME) ON DELETE CASCADE);

CREATE TABLE BOOK_AUTHORS(
  AUTHOR_NAME VARCHAR(20),
  BOOK_ID REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE,
  PRIMARY KEY(BOOK_ID,AUTHOR_NAME));
  
  
  
  
