# Creation of table:

CREATE TABLE STUDENT (
  SNUM INT PRIMARY KEY,
  SNAME VARCHAR(20),
  MAJOR VARCHAR(10),
  LEV VARCHAR(20),
  AGE INT);


CREATE TABLE FACULTY (
  FID INT PRIMARY KEY,
  FNAME VARCHAR(20),
  DEPID INT);
  

CREATE TABLE CLASS (
  Cname VARCHAR(20) PRIMARY KEY,
  MEETS_AT VARCHAR(20),
  ROOM VARCHAR(20),
  FID REFERENCES FACULTY(FID) ON DELETE SET NULL);


CREATE TABLE ENROLLED (
SNUM REFERENCES STUDENT(SNUM),
CNAME REFERENCES CLASS(CNAME));


#Queries:

SELECT DISTINCT S.SNUM, S.SNAME FROM STUDENT S,CLASS C, ENROLLED E,FACULTY F WHERE S.SNUM =
E.SNUM AND E.CNAME = C.CNAME AND C.FID = F.FID AND F.FNAME = 'RAKESH' AND S.LEV = 'JR'
ORDER BY SNUM;


SELECT MAX(S.AGE) AS AGE FROM STUDENT S WHERE (S.MAJOR = 'HISTORY') OR S.SNUM IN (SELECT E.SNUM
FROM CLASS C , ENROLLED E, FACULTY F WHERE E.CNAME = C.CNAME AND C.FID = F.FID AND F.FNAME =
'RAVI');


SELECT DISTINCT S.SNAME FROM STUDENT S WHERE S.SNUM IN (SELECT E1.SNUM FROM ENROLLED E1,ENROLLED
E2, CLASS C1, CLASS C2 WHERE E1.SNUM = E2.SNUM AND E1.CNAME <> E2.CNAME AND E1.CNAME =
C1.CNAME AND E2.CNAME = C2.CNAME AND C1.MEETS_AT = C2.MEETS_AT);


SELECT DISTINCT F.FNAME , COUNT(*) AS COURSECOUNT FROM CLASS C , FACULTY F WHERE C.FID NOT IN
(SELECT FID FROM CLASS WHERE ROOM IN (SELECT ROOM FROM CLASS WHERE ROOM!= 'R128')) AND C.FID =
F.FID GROUP BY F.FNAME;


CREATE VIEW STUDENT_DETAILS AS 
SELECT S.SNUM, S.SNAME, S.MAJOR, S.LEV, S.AGE,
E.CNAME FROM STUDENT S, ENROLLED E WHERE S.SNUM = E.SNUM;
