# Creation of Tables: 

CREATE TABLE PUBLISHER(
  NAME VARCHAR(25) PRIMARY KEY,
  ADDRESS VARCHAR(50),
  PHONE VARCHAR(13));

CREATE TABLE BOOK(
  BOOK_ID INTEGER PRIMARY KEY,
  TITLE VARCHAR(20),
  PUB_YEAR VARCHAR(20),
  PUBLISHER_NAME REFERENCES PUBLISHER(NAME) ON DELETE CASCADE);

CREATE TABLE BOOK_AUTHORS(
  AUTHOR_NAME VARCHAR(20),
  BOOK_ID REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE,
  PRIMARY KEY(BOOK_ID,AUTHOR_NAME));

CREATE TABLE LIBRARY_BRANCH(
  BRANCH_ID INTIGER PRIMARY KEY,
  BRANCH_NAME VARCHAR(20),
  ADDRESS VARCHAR(20));

CREATE TABLE BOOK_COPIES(
  NO_OF_COPIES INTEGER,
  BOOK_ID REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE,
  BRANCH_ID REFERENCES LIBRARY_BRANCH(BRANCH_ID) ON DELETE CASCADE,
  PRIMARY KEY(BOOK_ID,BRANCH_ID));
  
CREATE TABLE CARD(
  CARD_NO INTEGER PRIMARY KEY);
  
CREATE TABLE BOOK_LENDING(
  DATE_OUT DATE,
  DUE_DATE DATE,
  BOOK_ID REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE,
  BRANCH_ID REFERENCES LIBRARY_BRANCH(BRANCH_ID) ON DELETE CASCADE,
  CARD_NO REFERENCES CARD(CARD_NO) ON DELETE CASCADE,
  PRIMARY KEY(BOOK_ID,BRANCH_ID,CARD_NO));

#Queries:

SELECT B.BOOK_ID, B.TITLE, B.PUBLISHER_NAME, A.AUTHOR_NAME, C.NO_OF_COPIES, L.BRANCH_ID
FROM BOOK B, BOOK_AUTHORS A, BOOK_COPIES C, LIBRARY_BRANCH L
WHERE B.BOOK_ID = A.BOOK_ID AND B.BOOK_ID = C.BOOK_ID AND L.BRANCH_ID = C.BRANCH_ID;


SELECT BL.CARD_NO
FROM CARD C, BOOK_LENDING BL
WHERE DATE_OUT BETWEEN '01-JAN-17' AND '30-JUN-17' GROUP BY BL.CARD_NO HAVING COUNT(*) > 3;


CREATE VIEW V_PUBLICATION AS 
SELECT PUB_YEAR FROM BOOK;


CREATE VIEW V_BOOK AS 
SELECT B.BOOK_ID, B.TITLE, C.NO_OF_COPIES 
FROM BOOK B, BOOK_COPIES C, LIBRARY_BRANCH L
WHERE B.BOOK_ID = C.BOOK_ID AND C.BRANCH_ID = L.BRANCH_ID;


DELETE FROM BOOK
WHERE BOOK_ID = 1;


