#Creation of tables:

CREATE TABLE FLIGHTS(
  Flno int primary key, 
  Source varchar(20), 
  Destination varchar(20),
  Distance int,
  DepartTime varchar(10),
  ArrivalTime varchar(10),
  PRICE int);


CREATE TABLE AIRCRAFT(
  AID int primary key,
  ANAME varchar(20),
  CRUSINGRANGE int);


CREATE TABLE EMPLOYEES(
  EID int primary key,
  ENAME varchar(20), 
  SALARY int);
  
  
  CREATE TABLE CERTIFIED(
    EID references EMPLOYEES(EID),
    AID references AIRCRAFT(AID));



#Queries:

SELECT ANAME FROM AIRCRAFT A, EMPLOYEES E, CERTIFIED C where A.AID = C.AID and E.EID = C.EID and
E.SALARY > 80000;


SELECT E.EID, MAX(CRUSINGRANGE) FROM EMPLOYEES E, CERTIFIED C, AIRCRAFT A where E.EID=C.EID and
A.AID = C.AID GROUP BY E.EID HAVING COUNT(*) > 3;


SELECT A.ANAME ,AVG(SALARY) FROM EMPLOYEES E, CERTIFIED C , AIRCRAFT A where C.EID = E.EID and A.AID
= C.AID and A.CRUSINGRANGE > 1000 GROUP BY A.ANAME;


(SELECT ENAME FROM EMPLOYEES E, CERTIFIED C WHERE C.Aid in
(SELECT A.AID FROM AIRCRAFT A, CERTIFIED C WHERE A.Aid not in
(SELECT AID FROM AIRCRAFT WHERE ANAME = 'BOEING' OR CRUSINGRANGE=3000)
GROUP BY A.AID
) AND E.EID = C.EID)
MINUS
(SELECT ENAME FROM EMPLOYEES E, CERTIFIED C WHERE C.AID in (
SELECT A.AID FROM AIRCRAFT A, CERTIFIED C WHERE A.AID in
(SELECT AID FROM AIRCRAFT WHERE ANAME = 'BOEING')
GROUP BY A.AID) AND E.EID = C.EID);

    --- ALTERNATIVE---

SELECT DISTINCT E.ENAME FROM EMPLOYEES E WHERE E.EID IN(
  SELECT C.EID FROM CERTIFIED C WHERE EXISTS(
    SELECT A.AID FROM AIRCRAFT A WHERE A.AID = C.AID
    AND A.CRUSINGRANGE > 1500) AND
  NOTEXISTS(SELECT A1.AID FROM AIRCRAFT A1 WHERE A1.AID = C.AID AND A1.ANMAE ='BOEING'));


SELECT EID, ENAME, SALARY FROM EMPLOYEES WHERE SALARY > (SELECT AVG(SALARY) FROM  EMPLOYEES) AND EID
NOT IN ( SELECT EID FROM CERTIFIED);
