#Creation of tables:

CREATE TABLE FLIGHTS(
  FLNO INT PRIMARY KEY, 
  SOURCE VARCHAR(20), 
  DESTINATION VARCHAR(20),
  DISTANCE INT,
  DEPARTTIME VARCHAR(10),
  ARRIVALTIME VARCHAR(10),
  PRICE INT);


CREATE TABLE AIRCRAFT(
  AID INT PRIMARY KEY,
  ANAME VARCHAR(20),
  CRUSINGRANGE INT);


CREATE TABLE EMPLOYEES(
  EID INT PRIMARY KEY,
  ENAME VARCHAR(20), 
  SALARY INT);
  
  
  CREATE TABLE CERTIFIED(
    EID REFERENCES EMPLOYEES(EID),
    AID REFERENCES AIRCRAFT(AID));


#Queries:

SELECT ANAME FROM AIRCRAFT A, EMPLOYEES E, CERTIFIED C WHERE A.AID = C.AID AND E.EID = C.EID AND
E.SALARY > 80000;


SELECT E.EID, MAX(CRUSINGRANGE) FROM EMPLOYEES E, CERTIFIED C, AIRCRAFT A WHERE E.EID=C.EID AND
A.AID = C.AID GROUP BY E.EID HAVING COUNT(*) > 3;


SELECT A.ANAME ,AVG(SALARY) FROM EMPLOYEES E, CERTIFIED C , AIRCRAFT A WHERE C.EID = E.EID AND A.AID
= C.AID AND A.CRUSINGRANGE > 1000 GROUP BY A.ANAME;


(SELECT ENAME FROM EMPLOYEES E, CERTIFIED C WHERE C.Aid IN
(SELECT A.AID FROM AIRCRAFT A, CERTIFIED C WHERE A.Aid NOT IN
(SELECT AID FROM AIRCRAFT WHERE ANAME = 'BOEING' OR CRUSINGRANGE=3000)
GROUP BY A.AID
) AND E.EID = C.EID)
MINUS
(SELECT ENAME FROM EMPLOYEES E, CERTIFIED C WHERE C.AID IN (
SELECT A.AID FROM AIRCRAFT A, CERTIFIED C WHERE A.AID IN
(SELECT AID FROM AIRCRAFT WHERE ANAME = 'BOEING')
GROUP BY A.AID) AND E.EID = C.EID);


SELECT EID, ENAME, SALARY FROM EMPLOYEES WHERE SALARY > (SELECT AVG(SALARY) FROM  EMPLOYEES) AND EID
NOT IN ( SELECT EID FROM CERTIFIED);
